CREATE TABLE `AppError` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `errorId` VARCHAR(191) NOT NULL,
  `source` VARCHAR(191) NOT NULL,
  `errorCode` VARCHAR(191) NOT NULL,
  `errorType` VARCHAR(191) NOT NULL DEFAULT 'backend',
  `severity` VARCHAR(191) NOT NULL DEFAULT 'medium',
  `status` VARCHAR(191) NOT NULL DEFAULT 'open',
  `message` TEXT NOT NULL,
  `stackTrace` TEXT NULL,
  `deviceId` VARCHAR(191) NULL,
  `deviceName` VARCHAR(191) NULL,
  `ownerId` VARCHAR(191) NULL,
  `ownerName` VARCHAR(191) NULL,
  `businessId` INTEGER NULL,
  `businessName` VARCHAR(191) NULL,
  `customerId` VARCHAR(191) NULL,
  `appVersion` VARCHAR(191) NULL,
  `osVersion` VARCHAR(191) NULL,
  `environment` JSON NULL,
  `rawDetails` JSON NULL,
  `resolvedAt` DATETIME(3) NULL,
  `resolvedBy` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `AppError_errorId_key`(`errorId`),
  INDEX `AppError_severity_idx`(`severity`),
  INDEX `AppError_status_idx`(`status`),
  INDEX `AppError_createdAt_idx`(`createdAt`),
  INDEX `AppError_businessId_idx`(`businessId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
