ALTER TABLE `AdminUser`
  ADD COLUMN `firstName` VARCHAR(191) NULL,
  ADD COLUMN `lastName` VARCHAR(191) NULL,
  ADD COLUMN `mobile` VARCHAR(191) NULL,
  ADD COLUMN `age` INTEGER NULL,
  ADD COLUMN `address` TEXT NULL;
