ALTER TABLE `Device`
  ADD COLUMN `scheduleEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `alwaysOn` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `scheduleStartTime` VARCHAR(191) NOT NULL DEFAULT '09:00',
  ADD COLUMN `scheduleEndTime` VARCHAR(191) NOT NULL DEFAULT '22:00';
