ALTER TABLE `Business`
  ADD COLUMN `showPrice` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `showDescription` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `showLogo` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `showCompanyName` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `showProductImage` BOOLEAN NOT NULL DEFAULT true;
