ALTER TABLE `Device`
  ADD COLUMN `showPrice` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `showDescription` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `showLogo` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `showCompanyName` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `showProductImage` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `headingFontScale` DOUBLE NOT NULL DEFAULT 1.0,
  ADD COLUMN `nameFontScale` DOUBLE NOT NULL DEFAULT 1.0,
  ADD COLUMN `descriptionFontScale` DOUBLE NOT NULL DEFAULT 1.0,
  ADD COLUMN `priceFontScale` DOUBLE NOT NULL DEFAULT 1.0;
